### PR TITLE
Various visual regressions

### LINKED ISSUE #791: DataTable Visual Regressions
**Bug Description**
Search box has some visual regressions:
- Font family
- Font colour
- Box sizing
- Overlap of text box and border of container
- Search icon position and sizing

### After
CleanShot 2023-04-21 at 12 30 46@2x

### Before
CleanShot 2023-04-21 at 12 32 22@2x

**Severity**
- [ ] High - I'm not able to use Evidence until this bug is fixed
- [ ] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [x] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

### PR DESCRIPTION
**Pull request by csjh**
### Description

Fixes #791, #798, #736

### Before / After
image
image
---
image
image
---
image
image
---
image
image
---
image
image

### Checklist

- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

### CODE REVIEW

File: sites/example-project/src/components/viz/ErrorChart.svelte [hunk 1]
```diff
@@ -17,9 +17,9 @@
 			class:w-[7.8em]={chartType.includes('Value')}
 		>
 			{error}
+			{#if dev && error === MissingCredentialsError}
+				<br><a class="credentials-link" href="/settings"> Add credentials &rarr;</a>
```
Comment (archiewood) [inline sites/example-project/src/components/viz/ErrorChart.svelte]: Should we add a non breaking space between the word "credentials" and the right arrow?
In your screenshot there appears to be a linebreak.

(Or else we could remove the right arrow completely)

Comment (csjh) [reply sites/example-project/src/components/viz/ErrorChart.svelte]: Good point, looks nicer with no breaks:
image
