### PR TITLE
fixed string handling for prop values

### LINKED ISSUE #2668: [Bug]: Slider should support numbers as strings
### Describe the bug

`defaultValue` and `step` props currently do not convert string inputs into numbers, causing the component to break in some scenarios. Same logic for `min` and `max` should be applied to those props

### Steps to Reproduce

Add slider with `defaultValue` and `step` specified

### Logs

_No response_

### System Info

_No response_

### Severity

annoyance

### Additional Information, or Workarounds

Wrap numbers with `{}`. E.g.,:

```
<Slider
   defaultValue={0.11}
   step={0.02}
/>
```

### PR DESCRIPTION
**Pull request by kwongz**
### Description

fix #2668 

1. Fixed: ToNumber String Values to avoid errors
2. Improved: console.error for NaN values

`<Story
	name="handle string values"
	args={{
		defaultValue: '18',
		fmt: 'usd0',
		steps: '2',
		max: '20',
		min: '0'
	}}
/>`

https://github.com/user-attachments/assets/7c02e1f7-cc94-4ff3-85a3-30facc1860ed

### Checklist

- ~~[ ] For UI or styling changes, I have added a screenshot or gif showing before & after~~
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- ~~[ ] I have added to the docs where applicable~~
- ~~[ ] I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable~~

### CODE REVIEW

File: packages/ui/core-components/src/lib/atoms/inputs/slider/Slider.svelte [hunk 1]
```diff
@@ -25,35 +26,11 @@
 	/** @type {number|undefined} */
```
Comment (zachstence) [inline packages/ui/core-components/src/lib/atoms/inputs/slider/Slider.svelte:26]: Since `min` has a default value (`0`), it will never be `undefined`, so we can remove `undefined` from the type

```suggestion
	/** @type {number} */
```

File: packages/ui/core-components/src/lib/atoms/inputs/slider/Slider.svelte [hunk 2]
```diff
@@ -25,35 +26,11 @@
...
-		} else if (max < min) {
-			throw Error('max cannot be less than min');
-		}
-	} else {
-		max = 100;
-	}
-
 	/** @type {number} */
-	export let step;
+	export let step = undefined;
```
Comment (zachstence) [inline packages/ui/core-components/src/lib/atoms/inputs/slider/Slider.svelte:33]: We should default `step` to `1`

```suggestion
	export let step = 1;
```

File: packages/ui/core-components/src/lib/atoms/inputs/slider/Slider.svelte [hunk 3]
```diff
@@ -72,11 +49,61 @@
...
+	}
+
+	if (max !== undefined) {
+		max = validateNumber(max, 'max');
+		if (max !== undefined && min !== undefined) {
+			checkMinMax(min, max);
+		}
+	}
+
+	if (step !== undefined) {
```
Comment (zachstence) [inline packages/ui/core-components/src/lib/atoms/inputs/slider/Slider.svelte:87]: Since we're defaulting `step` to `1`, we don't need this check either

File: packages/ui/core-components/src/lib/atoms/inputs/slider/Slider.svelte [hunk 4]
```diff
@@ -72,11 +49,61 @@
...
+			checkMinMax(min, max);
+		}
+	}
+
+	if (max !== undefined) {
+		max = validateNumber(max, 'max');
+		if (max !== undefined && min !== undefined) {
+			checkMinMax(min, max);
+		}
+	}
```
Comment (zachstence) [inline packages/ui/core-components/src/lib/atoms/inputs/slider/Slider.svelte:85]: `checkMinMax` is called twice, it only needs to be called once

```suggestion
	if (min !== undefined) {
		min = validateNumber(min, 'min');
	}
	if (max !== undefined) {
		max = validateNumber(max, 'max');
	}
	if (max !== undefined && min !== undefined) {
		checkMinMax(min, max);
	}
```

**Review by zachstence — CHANGES_REQUESTED** [review]

**Review by zachstence — APPROVED** [review]
