### PR TITLE
Fix BQ builds

### LINKED ISSUE #1239: Netlify cannot read bigquery credentials with newline characters
## Steps To Reproduce

1. Configure a BigQuery connection using a service account (json key) in evidence locally.
2. Deploy your project to netlify and copy the variables from the deployment settings page to your Netlify environment variables.
3. Deploy your build. The build will succeed, but SQL queries will not execute.

### Environment

- Node version (`node -v`): 20.0.0
- npm version (`npm -v`): 9.6.4
- OS: MacOS Ventura 13.4.1
- Browser: Brave
- Database: BigQuery (native table)

## Expected Behavior

The SQL queries should execute.

## Actual Behaviour

The SQL queries return errors (as do any visuals that use them).
Screenshot 2023-10-06 at 00 50 55
Screenshot 2023-10-06 at 00 51 14

## Workarounds

No known workaround currently, as I did not de-authorise my BigQuery service account.

### PR DESCRIPTION
**Pull request by archiewood**
### Description

Fixes #1239 

### Checklist

- [ ] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

### CODE REVIEW

File: packages/bigquery/index.cjs [hunk 1]
```diff
@@ -84,7 +84,9 @@ const getCredentials = (database = {}) => {
 			projectId: database.project_id ?? getEnv(envMap, 'projectId'),
 			credentials: {
 				client_email: database.client_email ?? getEnv(envMap, 'credentials', 'clientEmail'),
-				private_key: (database.private_key ?? getEnv(envMap, 'credentials', 'privateKey'))?.trim()
+				private_key: (database.private_key ?? getEnv(envMap, 'credentials', 'privateKey'))
+					?.replace(/\\n/g, '\n')
```
Comment (archiewood) [inline packages/bigquery/index.cjs:88]: this replace operation is used to convert a string representation of newlines ("\n") into actual newline characters.

**Review by csjh — APPROVED** [review]
LGTM
