### PR TITLE
1117 - Make Column component reactive to props changing.

### LINKED ISSUE #1117: DataTable Column titles aren't reactive
## Steps To Reproduce

Have a data table Column's title prop be assigned to a reactive svelte variable. When the variable value changes, the column title does not.

We need this because we have filters that change aggregation dynamically, so the column title should sometimes change dynamically.

## Expected Behavior

Column title updates dynamically.

## Actual Behaviour

Column title does not change.

## Workarounds

Use a column title that makes sense regardless of context.

### PR DESCRIPTION
**Pull request by jdimmerman**
### Description

Make Column component reactive to props changing.

Fixes #1117 

### Checklist

- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

### CODE REVIEW

File: packages/core-components/src/lib/unsorted/viz/Column.svelte [hunk 1]
```diff
@@ -56,35 +56,61 @@
...
+					...d.columns.slice(0, matchingIndex),
+					options,
+					...d.columns.slice(matchingIndex + 1)
+				];
+			}
+			return d;
+		});
+	};
+	$: id,
+		title,
```
Comment (jdimmerman) [inline packages/core-components/src/lib/unsorted/viz/Column.svelte:102]: Is there a more succinct way of effectively indicating "all props" here?

Comment (ItsMeBrianD) [reply packages/core-components/src/lib/unsorted/viz/Column.svelte:102]: You may be able to reference `$$props`, but I'm not sure if that's reactive

Comment (jdimmerman) [reply packages/core-components/src/lib/unsorted/viz/Column.svelte:102]: After some quick testing, getting unexpected results and bad performance. I think it gets a new reference every time even if the specific constituent props didn't change, which would cause the columns to constantly rerender.

Comment (ItsMeBrianD) [reply packages/core-components/src/lib/unsorted/viz/Column.svelte:102]: Ah yeah that's not ideal

Options could be declared this way potentially:

```javascript
$: options = {
    id, title, // ...
}
```

Comment (ItsMeBrianD) [reply packages/core-components/src/lib/unsorted/viz/Column.svelte]: Awesome! I'm glad that worked

File: packages/core-components/src/lib/unsorted/viz/Column.svelte [hunk 2]
```diff
@@ -66,7 +66,8 @@
 	export let deltaSymbol = true;
 	deltaSymbol = deltaSymbol === 'true' || deltaSymbol === true;
 
-	let options = {
+	let options;
```
Comment (ItsMeBrianD) [inline packages/core-components/src/lib/unsorted/viz/Column.svelte:69]: You don't actually _need_ this declaration; Svelte adds it automatically for you based on the line below

Comment (archiewood) [inline packages/core-components/src/lib/unsorted/viz/Column.svelte:69]: Is this necessary now you have the `$: options `

File: packages/core-components/src/lib/unsorted/viz/Column.svelte [hunk 3]
```diff
@@ -83,8 +84,20 @@
 		showValue: showValue
 	};
 
-	props.update((d) => {
-		d.columns.push(options);
-		return d;
-	});
+	const updateProps = () => {
```
Comment (ItsMeBrianD) [inline packages/core-components/src/lib/unsorted/viz/Column.svelte:87]:
```suggestion
        /**
         * Ensures that column props (e.g. title) are reflected in the table's state.
         * Without this function, props are only used on first render, and are not reactive
         * @returns {void}
         */
	const updateProps = () => {
```

**Review by ItsMeBrianD — APPROVED** [review]
A small note, and some comments

This looks great, thank you for submitting it!

File: packages/core-components/src/lib/unsorted/viz/Column.svelte (hunk 2 above)
Comment (jdimmerman) [reply packages/core-components/src/lib/unsorted/viz/Column.svelte]: TIL: nope!

Comment (jdimmerman) [reply packages/core-components/src/lib/unsorted/viz/Column.svelte]: Very cool, I didn't know that. Removed, thanks

**Comment by jdimmerman** [comment]
@ItsMeBrianD do I need to do anything here to kick off the tests following your approval?

**Comment by ItsMeBrianD** [comment]
> @ItsMeBrianD do I need to do anything here to kick off the tests following your approval?

Yes, I just kicked them off 🚀

**Comment by jdimmerman** [comment]
> > @ItsMeBrianD do I need to do anything here to kick off the tests following your approval?
> 
> Yes, I just kicked them off 🚀

@ItsMeBrianD same thing for the Tests-sources by any chance?

**Comment by ItsMeBrianD** [comment]
> > > @ItsMeBrianD do I need to do anything here to kick off the tests following your approval?
> > 
> > 
> > Yes, I just kicked them off 🚀
> 
> @ItsMeBrianD same thing for the Tests-sources by any chance?

I'm not sure why those haven't been kicked off; I don't have anything to start them

**Comment by ItsMeBrianD** [comment]
Looks like I could do it manually

**Comment by archiewood** [comment]
Approval has to be done separately for the docs / workspace builds and the tests. Not sure why tbh,

**Comment by jdimmerman** [comment]
(This is probably obvious but just in case) I don't have access to merge, I'm just assuming someone on your team will when it looks good. Thanks!
