### PR TITLE
Fix page query HMR

### LINKED ISSUE #2926: [Bug]: Query HMR broken
### Describe the bug

I have to restart the dev server to get the page to reflect edits to queries. Not always, but often. Ever since the latest update.

### System Info

```Shell
System:
    OS: macOS 15.1.1
    CPU: (14) arm64 Apple M3 Max
    Memory: 4.72 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.asdf/installs/nodejs/20.12.2/bin/node
    Yarn: 1.22.22 - ~/.asdf/installs/nodejs/20.12.2/bin/yarn
    npm: 10.8.3 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 131.0.6778.140
    Safari: 18.1.1
  npmPackages:
    @evidence-dev/bigquery: ^2.0.9 => 2.0.9 
    @evidence-dev/core-components: ^5.0.1 => 5.0.1 
    @evidence-dev/csv: ^1.0.14 => 1.0.14 
    @evidence-dev/databricks: ^1.0.8 => 1.0.8 
    @evidence-dev/duckdb: ^1.0.13 => 1.0.13 
    @evidence-dev/evidence: ^40.0.1 => 40.0.1 
    @evidence-dev/motherduck: ^1.0.4 => 1.0.4 
    @evidence-dev/mssql: ^1.1.2 => 1.1.2 
    @evidence-dev/mysql: ^1.1.4 => 1.1.4 
    @evidence-dev/postgres: ^1.0.7 => 1.0.7 
    @evidence-dev/snowflake: ^1.2.2 => 1.2.2 
    @evidence-dev/sqlite: ^2.0.7 => 2.0.7 
    @evidence-dev/trino: ^1.0.9 => 1.0.9 
    @sveltejs/adapter-static: ^3.0.6 => 3.0.6 
    autoprefixer: ^10.4.20 => 10.4.20 
    postcss: ^8.4.47 => 8.4.49 
    tailwindcss: ^3.4.13 => 3.4.16
```

### Severity

serious, but I can work around it

### Additional Information, or Workarounds

major productivity hit :(

### PR DESCRIPTION
**Pull request by csjh**
### Description

Fixes #2926 

Deletes prerendered queries on HMR so nothing leaks through from edited queries

We could implement some level of caching so non-edited queries aren't deleted, not sure if it's worth the added complexity or not

### Checklist

- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

### CODE REVIEW

**Review by zachstence — APPROVED** [review]

File: packages/lib/preprocess/src/process-queries.cjs [hunk 1]
```diff
@@ -64,6 +64,11 @@ const createDefaultProps = function (filename, componentDevelopmentMode, duckdbQ
 			return `
                 // Update external queries
                 if (import.meta?.hot) {
+					import.meta.hot.on("vite:beforeUpdate", () => {
+						// remove all prerendered queries
+						delete props.data;
```
Comment (ItsMeBrianD) [inline packages/lib/preprocess/src/process-queries.cjs:69]: Why not use the svelte invalidation methods?

Comment (csjh) [reply packages/lib/preprocess/src/process-queries.cjs:69]: because i forgot about their existence 😔

Comment (csjh) [reply packages/lib/preprocess/src/process-queries.cjs:69]: actually I don't think they'd work, `invalidateAll` just reruns the load function on the client side, but queries are only SSR'd on the server, so `invalidateAll` just ends up fetching the same outdated data
